version: "3.9"
services:
  wasim-dev:
    hostname: 'wasim-dev'
    build:
      context: ./
      dockerfile: ./docker/dev.dockerfile
      args:
        USERSHELL: zsh  # can be overridden with --build-arg on the command line
      network: host
    volumes:
      - .:/root/wa_simulator
      - ~/.ssh/:/root/.ssh/           # Non-functioning in windows
      - ~/.gitconfig:/root/.gitconfig # Non-functioning in windows
    tty: true
    working_dir: /root/
    environment:
      DISPLAY: "host.docker.internal:0" 
