version: "3.9"
services:
  wasim-dev:
    hostname: 'wasim-dev'
    image: wiscauto/wa_simulator:develop
    build:
      context: ./
      dockerfile: ./docker/dev.dockerfile
      network: host
    working_dir: /root/
    environment:
      - PYTHONUNBUFFERED=1
  wasim-prod:
    hostname: 'wasim-prod'
    image: wiscauto/wa_simulator:latest
    build:
      context: ./
      dockerfile: ./docker/dev.dockerfile
      network: host
    working_dir: /root/
