version: "3.9"
services:
  wasim-dev:
    hostname: 'wasim-dev'
    container_name: 'wasim-dev'
    image: wiscauto/wa_simulator:develop
    build:
      context: ./
      dockerfile: ./docker/dev.dockerfile
      network: host
    working_dir: /root/
  wasim-prod:
    hostname: 'wasim-prod'
    container_name: 'wasim-prod'
    image: wiscauto/wa_simulator:latest
    build:
      context: ./
      dockerfile: ./docker/prod.dockerfile
      network: host
  wasim-chrono:
    hostname: 'wasim-chrono'
    container_name: 'wasim-chrono'
    image: wiscauto/wa_simulator:chrono
    build:
      context: ./
      dockerfile: ./docker/chrono.dockerfile
      network: host
