name: github pages

on:
  push:
    branches:
      - develop

jobs:
  docs:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - uses: seanzhengw/sphinx-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
